### ISSUE TITLE
Eclipse-Mars script missing..

### ISSUE THREAD

**Issue by sggr57a** [autopkg/rtrouton-recipes#10]
I'm getting an error on your preinstall script whenever it runs the JSS recipe.  It's looking for the script in /Volumes/CasperShare/Scripts for some reason.

**Comment by rtrouton** [comment]
You may need to add the `JSS_MIGRATED` preference to your AutoPkg settings:

[https://github.com/sheagcraig/JSSImporter](https://github.com/sheagcraig/JSSImporter) - search on the page for `JSS_MIGRATED`.

For more background on why that's needed, please see here:

[https://github.com/sheagcraig/JSSImporter/issues/19#issuecomment-72467351](https://github.com/sheagcraig/JSSImporter/issues/19#issuecomment-72467351)

**Comment by sggr57a** [comment]
"JSS_MIGRATED: Boolean. If you have "migrated" your JSS (uses the web interface to edit scripts), set to True. Defaults to False. This only really comes into play if you have an AFP or SMB share and have migrated."

Why would I need to add it if this is a new server?  It just comes down to the validity of the recipe doesn't it?
