### ISSUE TITLE
EndNote 20 - MunkiImporter requires missing argument pkg_path

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/rtrouton-recipes#107]
Thanks for update to EndNote 20 but there is an error:

The following recipes failed:
    endnote20.munki
        MunkiImporter requires missing argument pkg_path

The following recipes failed:
    endnote20.pkg
        MunkiImporter requires missing argument pkg_path

If you look at previous recipes (older versions) the EndNote20.install.recipe is missing (or is this not required any more?)

**Comment by rtrouton** [comment]
Please talk to @oliverweinm, as he sent in the Endnote 20 recipes.

**Comment by Peter-Erik** [comment]
OK will do that thanks rtrouton

**Comment by oliverweinm** [comment]
Strange, thanks for the tip. I will look into it @Peter-Erik

**Comment by Peter-Erik** [comment]
@oliverweinm - Thanks for making this recipe take your time

**Comment by ckostovny** [comment]
I see the same behavior as @Peter-Erik, I'm not using Munki. Is this happening because EndNote20.pkg.recipe has ParentRecipe set to com.github.rtrouton.munki.EndNote20 instead of com.github.rtrouton.download.EndNote20? Thanks for any assistance.

**Comment by rtrouton** [comment]
I've updated the ParentRecipe in the EndNote20 pkg recipe and it looks like the pkg recipe now works OK. I have not tested the .munki recipe.

**Comment by oliverweinm** [comment]
Okay, it really seems to have been a wrong value for the parent recipe key in the munki recipe (and the pkg recipe which has now been fixed by @rtrouton, thanks for that!). 
It's been fixed in https://github.com/autopkg/rtrouton-recipes/pull/109 and the .munki recipe now runs for me(, as does the .pkg recipe). 
I'm still baffled as to how I didn't catch that. I apologize for any inconveniences.

**Comment by Peter-Erik** [comment]
Strange still error with .munki   .pkg and .download works now

The following recipes failed:
    endnote20.munki
        MunkiImporter requires missing argument pkg_path

**Comment by oliverweinm** [comment]
Hi @Peter-Erik , that's (hopefully) because my pull request #109 hasn't been merged/accepted yet.

**Comment by rtrouton** [comment]
Now merged.

**Comment by Peter-Erik** [comment]
Sorry was to fast - need to read first then check ;-)

**Comment by oliverweinm** [comment]
Hi @Peter-Erik,
the recipe seems to be working for me now. Can you confirm the same?

**Comment by Peter-Erik** [comment]
Hi @oliverweinm works! - thanks for your effort.
