### ISSUE TITLE
ImageJ Recipes

### ISSUE THREAD

**Issue by macmule** [autopkg/rtrouton-recipes#125]
Logging this as an fyi..

It looks like the Imagej recipe downloads the .app, which contains (at the time of writing) 1.53a.. you can then upgrade in-app to 1.53k.. this is by downloading the il.jar as per: https://imagej.nih.gov/ij/upgrade/index.html

I'll see if we can sort this so we download the .jar and .app, then combine

**Comment by rtrouton** [comment]
Following up on this - Did you find a solution to the app download being an older one?

**Comment by macmule** [comment]
Thanks for the reminder, still needed..

If you check , you'll see:

> The easiest way to upgrade to the latest version of ImageJ is to use the Help>Update ImageJ command, available in version 1.41 or later.The Update ImageJ command downloads the latest ij.jar file (the core of ImageJ) fromwsr.imagej.net/jars/ij.jar. Alternatively, it will download the "daily build" ij.jar file fromwsr.imagej.net/download/daily-build if "daily build" is selected from the drop down menu. The Java source code for ImageJ is available at image.nih.gov/ij/download/src/.

Which is what we need to copy.. as well as amending the .app too (doable as not signed).. i'll look into this shortly.

**Comment by macmule** [comment]
PR done
