### ISSUE TITLE
CitrixWorkspace.download.recipe Issue

### ISSUE THREAD

**Issue by el2493** [autopkg/rtrouton-recipes#127]
The URLTextSearcher processor no longer seems to work. The re_pattern is looking for:

<string>(?P&lt;DYNAMIC_URL&gt;//downloads.citrix.com/[\d]+/CitrixWorkspaceApp\.dmg\?__gda__\=[\w]+)</string>

However, the latest download URL is:

https://downloads.citrix.com/19721/CitrixWorkspaceApp.dmg?__gda__=exp=1627404022~acl=/*~hmac=56173a1b452e01aed4d6a2509a4b2e653d006792e10613fffe06292798484511

So when URLTextSearcher runs, it only captures part of the URL and then stops:

https://downloads.citrix.com/19721/CitrixWorkspaceApp.dmg?__gda__=exp

I'm not sure what the format of the URL will be in the next release, but for right now I believe either of these would work:

<string>(?P&lt;DYNAMIC_URL&gt;//downloads.citrix.com/[\d]+/CitrixWorkspaceApp\.dmg\?__gda__\=exp\=(\w|\~|\=)+/(\w|\*|\~|\=)+)</string>

or

<string>(?P&lt;DYNAMIC_URL&gt;//downloads.citrix.com/[\d]+/CitrixWorkspaceApp\.dmg\?__gda__\=exp\=[\d]+~acl\=/\*~hmac\=[\d|\w]+)</string>

**Comment by el2493** [comment]
(credit to @mpanighetti for the first amended code to get the download)

**Comment by rtrouton** [comment]
`CitrixWorkspace.download` recipe has been updated with the following regex:

`(?P&lt;DYNAMIC_URL&gt;//downloads.citrix.com/[\d]+/CitrixWorkspaceApp\.dmg\?__gda__\=exp\=(\w|\~|\=)+/(\w|\*|\~|\=)+)`
