### ISSUE TITLE
Prism.download recipe

### ISSUE THREAD

**Issue by cumcitjamfadmin** [autopkg/rtrouton-recipes#137]
Could https://github.com/autopkg/rtrouton-recipes/blob/master/Prism/Prism.download.recipe be updated to look for the latest version of Prism? It currently has this block:

<key>MAJOR_VERSION</key>
<string>8</string>

Which finds v. 8.4.3. As per Prism's website (https://www.graphpad.com/updates/) the latest version is v. 9.3.0. I tried creating a copy of the recipe and changing MAJOR_VERSION to 9 and it downloaded 9.3.0, so the recipe would just need that to be updated.

**Comment by rtrouton** [comment]
Updated: https://github.com/autopkg/rtrouton-recipes/commit/e9a3b6176774690c7416c062ed999328bd0ede1a

**Comment by cumcitjamfadmin** [comment]
Thanks! Could you also update https://github.com/autopkg/rtrouton-recipes/blob/master/JSS/Prism.jss.recipe? It has the same MAJOR_VERSION issue.

**Comment by rtrouton** [comment]
I've now removed the `MAJOR_VERSION` key from all Prism recipes except for the `.download` recipe.
