### ISSUE TITLE
VMware-Tools does not download the latest version

### ISSUE THREAD

**Issue by mikeknight85** [autopkg/rtrouton-recipes#144]
VMware-Tools is downloading 11.5.6, latest version would be 12.0.0

**Comment by homebysix** [comment]
You can adjust this by providing a `VERSION_SERIES` input variable set to `12.0.0` in your override.

I've also submitted a change to the provider processor that adjusts the default to 12: https://github.com/autopkg/rtrouton-recipes/pull/145
