### ISSUE TITLE
AdobeReaderDC recipe fails

### ISSUE THREAD

**Issue by mstevens-gc** [autopkg/rtrouton-recipes#146]
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2200120112/AcroRdrDC_2200120112_MUI.dmg', '--fail', '--output', '<user path>/Library/AutoPkg/Cache/local.pkg.AdobeReaderDC/downloads/tmpqv3ehsqi']' returned non-zero exit status 22.
Failed.

**Comment by rtrouton** [comment]
Root issue is in the following recipe:

https://github.com/autopkg/recipes/blob/master/AdobeReader/AdobeReaderDC.download.recipe

I recommend opening an issue with the maintainers of the [recipes](https://github.com/autopkg/recipes) repo.

**Comment by homebysix** [comment]
We already [looked into](https://github.com/autopkg/recipes/issues/424#issuecomment-1097003091) this issue, and it appears to be a problem on Adobe's end. It was brought to their attention in Slack.

**Comment by mstevens-gc** [comment]
For what it's worth, this recipe works and pulls the latest update. https://github.com/autopkg/novaksam-recipes/tree/master/Adobe%20Acrobat%20Reader%20DC%20Updates
