### ISSUE TITLE
Double escaping URL space in MountainDuck.download

### ISSUE THREAD

**Issue by AllPurposeBen** [autopkg/rtrouton-recipes#152]
When running [MountainDuck.download](https://github.com/autopkg/rtrouton-recipes/blob/master/MountainDuck/MountainDuck.download.recipe), I get a failure in the curl because a URL encoded space got double escaped into a `%2520`.

In what I think is a similar issue to https://github.com/autopkg/homebysix-recipes/pull/347, in MountainDuck.download, the output from `SparkleUpdateInfoProvider` is getting a double escaped space:
```
SparkleUpdateInfoProvider: Found URL https://dist.mountainduck.io/Mountain%2520Duck-4.12.1.19928.zip
```
The output from the [raw sparkle RSS](https://version.mountainduck.io/changelog.rss) looks right and matches the URL from download button on their site:
```
sparkle:edSignature="VaO9yj8OsvqTIdwnCyDiJXgGIOF2CHIZfkroMAVJddjWjKokD/QpbKx/YxDFE41u9pp3Yj/WtsG+GSh1eEEDCg==" url="https://dist.mountainduck.io/Mountain%20Duck-4.12.1.19928.zip" type="application/octet-stream"/>
```
...but `SparkleUpdateInfoProvider` seems to be mangling it. 

Not sure if the[ same fix](https://github.com/autopkg/homebysix-recipes/pull/347/commits) should apply or if this or if it might be something goofy in `SparkleUpdateInfoProvider` worth raising in the main[ autopkg repo after all](https://github.com/autopkg/autopkg/issues/695)?

**Comment by rtrouton** [comment]
Looks like @homebysix 's fix for the Screens recipe works here as well.

**Comment by rtrouton** [comment]
This commit (https://github.com/autopkg/rtrouton-recipes/commit/4f8827836ddcc930ee32f344c9c83c3835ef114e) seems to have fixed the issue for me. Would you please confirm?

**Comment by AllPurposeBen** [comment]
Yep, that solved the issue. Thanks!
