### ISSUE TITLE
MicrosoftOffice365Suite and com.github.keeleysam.recipes.GoogleTalkPlugin/MunkiPkginfoReceiptsEditor

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/rtrouton-recipes#158]
Hi @rtrouton just wanted to point you to this: https://github.com/autopkg/keeleysam-recipes/issues/148

Looks like this processor is now part of autopkg core, can you adjust the recipe at https://github.com/autopkg/rtrouton-recipes/blob/master/MicrosoftOffice365Suite/MicrosoftOffice365Suite.munki.recipe#L73 ? Thanks!

**Comment by vmiller** [comment]
Pull request https://github.com/autopkg/rtrouton-recipes/pull/159 attempts to address this issue.
