### ISSUE TITLE
Update Citrix Workspace.download to Universal version

### ISSUE THREAD

**Issue by da4ftso** [autopkg/rtrouton-recipes#161]
Citrix has released a universal version of Workspace, v22.10.0, at: https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-native-support-for-silicon-mac.html

**Comment by rtrouton** [comment]
I've posted new recipes to support folks who need the Universal version of Citrix Workspace via the alternate download link:

- [com.github.rtrouton.download.citrixworkspaceuniversal](https://github.com/autopkg/rtrouton-recipes/blob/master/CitrixWorkspace/CitrixWorkspaceUniversal.download.recipe)
- [com.github.rtrouton.pkg.citrixworkspaceuniversal](https://github.com/autopkg/rtrouton-recipes/blob/master/CitrixWorkspace/CitrixWorkspaceUniversal.pkg.recipe)
- [com.github.rtrouton.jamf.citrixworkspaceuniversal](https://github.com/autopkg/rtrouton-recipes/blob/master/Jamf_Upload/CitrixWorkspaceUniversal.jamf.recipe)
