### ISSUE TITLE
Microsoft Teams

### ISSUE THREAD

**Issue by paulc-us** [autopkg/rtrouton-recipes#166]
Getting this error when running the Microsoft Teams recipe.

`The following recipes failed:
    MicrosoftTeams.munki
        Error in local.munki.MicrosoftTeams: Processor: MunkiOptionalReceiptEditor: Error: You must specify at least one pkginfo repo path`

I have tried updating the repo and override.

**Comment by peterkelm** [comment]
+1. For now reverted back to the MSTeams recipe from https://github.com/autopkg/recipes/blob/master/MSOfficeUpdates/MSTeams.munki.recipe

**Comment by cbrherms** [comment]
Issue was upstream with a change  introduced in Autopkg 2.7
Looks to have been fixed in Autopkg 2.7.1
