### ISSUE TITLE
MicrosoftWord365.jss recipe not working

### ISSUE THREAD

**Issue by jaleksiewicz** [autopkg/rtrouton-recipes#169]
Getting the following error when trying to create an override with your recipe

<img width="266" alt="Screenshot 2023-02-28 at 10 59 46 AM" src="https://user-images.githubusercontent.com/115664820/221908567-f4a9ecd7-687d-4f52-bead-30dc07c1c0ce.png">

When I try to just run the recipe manually, I get this 
<img width="261" alt="Screenshot 2023-02-28 at 11 00 46 AM" src="https://user-images.githubusercontent.com/115664820/221908818-110abf48-5af7-4dea-b697-bd292dff8942.png">

I used your other individual M365.jss recipes the other day but this one is not working for me

**Comment by rtrouton** [comment]
The MicrosoftWord365.jss recipe includes a deprecation warning:

```The .jss recipes in the rtrouton-recipes repository will stop working in a future version of Jamf planned for late 2022. Please consider switching your JSSImporter workflows to JamfUploader instead. Details: https://grahamrpugh.com/2022/02/16/jssimporter-jamf-pro-api-token-auth.html```

The error message you're seeing in AutoPkgr tells you about that, and also tells you how to address that when creating an override.

<img width="266" alt="221908567-f4a9ecd7-687d-4f52-bead-30dc07c1c0ce" src="https://user-images.githubusercontent.com/618055/221911446-92e08247-85be-453f-b0e4-8fe82ae20c9d.png">

I would recommend moving away from using .jss recipes, including mine, as they're using the JSSImporter AutoPkg processors and they will stop working at some point in the near-ish future.
