### ISSUE TITLE
Can't Run or Create Override

### ISSUE THREAD

**Issue by gskibum** [autopkg/rtrouton-recipes#17]
I'm having an issue with the Office2016Suite.jss recipe.

When I either try to run it or create an override I get the error:

**Could not find parent recipe for com.github.rtrouton.pkg.Office2016Suite
A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] argument of type 'NoneType' is not iterable**

What confuses me is I have in the past successfully created this override with 3 other AutoPKG machines. And those overrides continue to work. But now I can't add it to 2 other AutoPKG machines. Also, on those same 3 machines I am also able to create new overrides of the Office2016Suite.jss recipe over and over again.

I just can't create an override on these other two AutoPKG machines.

On the two that are not cooperating with the Office2016Suite.jss recipe, I am able to create overrides of other recipes.

All 5 machines are VMs running Yosemite.

Any ideas?

![screen shot 2017-07-21 at 7 58 40 am](https://user-images.githubusercontent.com/13141708/28468332-ea468076-6def-11e7-9b97-dced3c0eb5bc.png)

**Comment by rtrouton** [comment]
On the affected machines, did you add the repo with the parent recipe? That will be `arubdesu-recipes`.

**Comment by gskibum** [comment]
Bullseye. That was exactly it. I did not realize that recipes are sometimes connected to each other in such a way that one requires another repo to be subscribed to.

Thank you.
