### ISSUE TITLE
Microsoft Excel, Word, Outlook, PowerPoint, OneNote need blocking applications array

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/rtrouton-recipes#173]
@rtrouton Can you add the blocking applications array to each of these apps? 

https://github.com/munki/munki/wiki/Blocking-Applications

Munki just starts the install, regardless if the app is running.
I observed incomplete installs when apps are running.

Thank you!

**Comment by rtrouton** [comment]
I don’t use Munki and the relevant .munki recipes were written by others, so I don’t have the relevant knowledge to add this information correctly. 

Pull requests to update the relevant recipes would be accepted.

**Comment by jelockwood** [comment]
@opus-nbo 
DataJar (an Apple partner) have written their own Munki recipes for Word, Excel, PowerPoint, Outlook and OneNote but not it appears OneDrive. These call @rtrouton download recipes. The DataJar Munki recipes do have blocking apps defined. Therefore one solution is to use the DataJar versions.

Alternatively you can add or copy/paste the blocking apps in to your own override recipes.

**Comment by opus-nbo** [comment]
@jelockwood Thanks, you are right! I overlooked that. I switched to the DataJar recipes.
