### ISSUE TITLE
Case sensitivity error from recipes

### ISSUE THREAD

**Issue by jelockwood** [autopkg/rtrouton-recipes#174]
@rtrouton 
I am currently adding additional recipes to a new Munki/Autopkg setup and using your Microsoft recipes.

I have noticed the following happens when I use your Microsoft OneDrive Munki recipe which calls your download recipe.

![Screenshot 2023-05-16 at 10 19 12](https://github.com/autopkg/rtrouton-recipes/assets/4300786/38c5695e-7e72-4ac7-a7a1-43a88667ab54)

I am guessing this may be down to your line 16 in your Munki recipe. In my case I am using a Synology NAS as the repo storage and I believe being Linux based it is using a case sensitive file system.

I think the fix would be to change line 16 to -

```
        <string>apps/microsoft</string>
```
This seems to have worked when I make this change via my recipe override.

**Comment by rtrouton** [comment]
Pull requests accepted to fix this. I don't use Munki and didn't write the .munki recipe; that was a contribution from someone else.
