### ISSUE TITLE
Malwarebytes download recipe pulling old version

### ISSUE THREAD

**Issue by aysiu** [autopkg/rtrouton-recipes#18]
Seems it's still pulling 1.2.6 instead of 3.0.1.

https://downloads.malwarebytes.com/file/mb3-mac will pull the new version.

**Comment by Tugzrida** [comment]
I've found the same thing. Problem is that the new version of MB is far more complicated than the old one. The dmg you link to contains an install and uninstall pkg. Just using Recipe Robot, it finds the install pkg fine but falls over as it can't pull out a version number. I'm not particularly experienced at AutoPkg so it'll likely take me a while to figure it out unless someone else wants to have a go.

**Comment by blackthroat** [comment]
Today I received "Code signature verification failed" from your munki recipe @aysiu, which is the child of this download recipe. Instead of using the `SPARKLE_FEED_URL`, using the `DOWNLOAD_URL` with the URL that @aysiu mentioned might be the easiest way to fix this?

**Comment by blackthroat** [comment]
The identifier in the Code signature verification changed from `com.malwarebytes.antimalware` to `Malwarebytes`

```$ codesign --display -r- --deep -v Malwarebytes-3.0.3.433.dmg 
Executable=/Users/blackthroat/Downloads/Malwarebytes-3.0.3.433.dmg
Identifier=Malwarebytes
Format=disk image
CodeDirectory v=20200 size=300 flags=0x0(none) hashes=1+6 location=embedded
Signature size=8923
Timestamp=Sep 19, 2017, 2:52:20 AM
Info.plist=not bound
TeamIdentifier=GVZRY6KDKR
Sealed Resources=none
designated => identifier Malwarebytes and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = GVZRY6KDKR`
```

**Comment by rtrouton** [comment]
Code signature has now been fixed.
