### ISSUE TITLE
Possible to update Prism "MAJOR_VERSION" from 9 to 10 ?

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/rtrouton-recipes#180]
There is an version update from GraphPad Prism v9 to v10 is it possible to change this in the recipe?

old situation:

<key>MAJOR_VERSION</key>
<string>9</string>

new situation: (after adjustment)

<key>MAJOR_VERSION</key>
<string>10</string>

thanks

**Comment by rtrouton** [comment]
Changed value of MAJOR_VERSION from 9 to 10.
