### ISSUE TITLE
Microsoft Teams recipe fails because of name change

### ISSUE THREAD

**Issue by ehjmx** [autopkg/rtrouton-recipes#182]
Microsoft changed the name from Microsoft Teams to Microsoft Teams classic in the downloaded package. This leads to an error in the Versioner Processor 
`File '/Users/autopkg/Library/AutoPkg/Cache/com.github.rtrouton.pkg.microsoftteams/downloads/payload/Microsoft Teams.app/Contents/Info.plist' was not found.`

This can be fixed by setting the value for the string as shown here: 
`<key>input_plist_path</key>`
`<string>%RECIPE_CACHE_DIR%/downloads/payload/Microsoft Teams classic.app/Contents/Info.plist</string>`

**Comment by rtrouton** [comment]
Addressing this issue with a new recipe for Microsoft Teams Classic:

https://github.com/autopkg/rtrouton-recipes/blob/master/MicrosoftTeams/MicrosoftTeamsClassic.pkg.recipe

The Teams recipe referenced in this issue has now been deprecated and should no longer be used.
