### ISSUE TITLE
Adobe CCDA download fails

### ISSUE THREAD

**Issue by AllPurposeBen** [autopkg/rtrouton-recipes#190]
Today I tried the universal CCDA download recipe and it failed out with this error:
```
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>http.*?://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/.*?/macarm64/ACCC.*?.dmg)',
           'result_output_var_name': 'match',
           'url': 'https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html
Failed.
```
...while doing the AppleSi section. The Intel parts ran without issue. I double checked and the same error is present in the AppleSi-only version of the download recipe.

Guessed that the url that the regex is looking for changed and after some trial and error, I think it did, I'm seeing something like this in the output of `https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html`:
```
https://ccmdls.adobe.com/AdobeProducts/StandaloneBuilds/ACCC/ESD/6.2.0/554/macarm64/ACCCx6_2_0_554.dmg
```

Toyed with the regex some and was able to get things working by changing the regex search patterns in my overrides to:
```
APPLE_SILICON_SEARCH_PATTERN: (?P<url>http.*?://ccmdls.adobe.com/AdobeProducts/StandaloneBuilds/ACCC/ESD/.*?/.*?/%APPLE_SILICON_ARCHITECTURE%/ACCC.*?.dmg)
INTEL_SEARCH_PATTERN: (?P<url>http.*?://ccmdls.adobe.com/AdobeProducts/StandaloneBuilds/ACCC/ESD/.*?/.*?/%INTEL_ARCHITECTURE%/ACCC.*?.dmg)
```

Those worked for me and my limited regex understanding. Not sure if those are right enough to warrant updating what's in the recipe in the repo to match but at any rate, the pattern looks like it did change at some point. 

Oddly enough, the old regex pattern still worked for the Intel version but so does the new one that works for AppleSi. 🤷 . I don't know enough of the history behind this recipe to guess at what changes Adobe is likely make.

I wanted to file an issue and get some input on this before I go to submitting a PR on changing those re search values. Am I on the right track or my fix is a fluke?

**Comment by rtrouton** [comment]
Most of the regex was fine, but part of the download URL needed to be updated:

From:

```
ccmdl.adobe.com/AdobeProducts/KCCC/CCD
```

To:

```
ccmdls.adobe.com/AdobeProducts/StandaloneBuilds/ACCC/ESD
```

The .download recipes have now been updated:

https://github.com/autopkg/rtrouton-recipes/commit/866e808c14388cea440a28b83840d9096eb2096d
