### ISSUE TITLE
Microsoft365 recipe query - not showing latest?

### ISSUE THREAD

**Issue by jelockwood** [autopkg/rtrouton-recipes#191]
@rtrouton @macmule 
Thank you for your recipes, these are working and currently for me are showing version 16.84.24041420 dating from April 2024.

_However…_

One some Macs Microsoft AutoUpdate is present also and has been popping up and listing a newer version than what Munki via AutoPkg and your recipes was listing. I had been presuming it was merely a timing issue but closer checking seems to suggest something different.

Microsoft AutoUpdater is currently listing 16.84.1.24042223 at least for Outlook and Powerpoint and these would be May updates. To confirm this was not a timing issue, I manually re-ran these recipes for AutoPkg and it has not pulled down any newer versions.

So the query is why does it appear that either these recipes are much slower to find updates than Microsoft AutoUpdate or are skipping some updates?

Note: The Macs are not set to use any beta or other early 365 releases.

**Comment by rtrouton** [comment]
That’s a question better directed towards Microsoft, as my AutoPkg recipes are using Microsoft’s download URLs which are supposed to have the latest versions.

**Comment by gregneagle** [comment]
You might also look at the Microsoft recipes in autopkg/recipes, as they use the same feeds as MAU to find the latest versions of things.
