### ISSUE TITLE
MicrosoftRemoteDesktop.download.recipe

### ISSUE THREAD

**Issue by kevinmcox** [autopkg/rtrouton-recipes#195]
The renaming of "Microsoft Remote Desktop" to "Windows App" went live today.

The package downloaded from the Microsoft FWLink for this recipe is named `Windows_App_11.0.0_installer.pkg`.

Just an FYI in case you want to adjust the recipe which currently renames the package `Microsoft_Remote_Desktop.pkg`

**Comment by rtrouton** [comment]
In place of that, I've posted new `.download` and `.pkg` recipes for Microsoft Windows App:

https://github.com/autopkg/rtrouton-recipes/tree/master/MicrosoftWindowsApp

I'll post a deprecation notice on the existing Microsoft Remote Desktop receipes next week, to avoid messing up someone's Read Only Friday. The Microsoft Remote Desktop `.pkg` recipe will have busted on its own, as certain assumptions in it no longer apply with the changed app name, but the download recipe should continue to work (albeit with the download package being named with a now-incorrect name.)

**Comment by kevinmcox** [comment]
Thanks Rich.
