### ISSUE TITLE
Overriding %NAME% on com.github.rtrouton.jss.AdobeCreativeCloudInstaller fails

### ISSUE THREAD

**Issue by discentem** [autopkg/rtrouton-recipes#20]
Getting the following error if I override `%NAME%`:

```
Processing local.jss.AdobeCreativeCloudInstaller...
WARNING: local.jss.AdobeCreativeCloudInstaller is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Error processing path '/private/tmp/dmg.OuGvCh/Adobe Creative Cloud.app' with glob.
Failed.

The following recipes failed:
    local.jss.AdobeCreativeCloudInstaller
        Error in local.jss.AdobeCreativeCloudInstaller: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.OuGvCh/Adobe Creative Cloud.app' with glob.
```

Override example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ParentRecipe</key>
	<string>com.github.rtrouton.jss.AdobeCreativeCloudInstaller</string>
	<key>Identifier</key>
	<string>local.jss.AdobeCreativeCloudInstaller</string>
	<key>Input</key>
	<dict>
                <key>NAME</key>
                <string>Adobe Creative Cloud</string>
		<key>CATEGORY</key>
		<string>Adobe</string>
		<key>CATEGORY</key>
		<string>Productivity</string>
		<key>GROUP_NAME</key>
		<string></string>
		<key>GROUP_TEMPLATE</key>
		<string></string>
		<key>POLICY_CATEGORY</key>
		<string>Productivity</string>
		<key>POLICY_TEMPLATE</key>
		<string>%RECIPE_DIR%/PolicyTemplates/selfservice.xml</string>
	</dict>

</dict>
</plist>
```

**Comment by gregneagle** [comment]
%NAME% really should be used to allow the admin customize _output_: like specifying the name of an output package or disk image, or the value of the "name" key in a Munki pkginfo. It should not be used in recipe steps where a recipe is looking for specific things in a package or disk image.

IOW, I should be able to name the output package of the pkg recipe "MyOrgAdobeCreativeCloudApp.pkg" if I want. That doesn't mean that the recipe should then look for an app named "MyOrgAdobeCreativeCloudApp.app" in the download.

If there is a concern the app name might change over time and you want to have an input variable so the admin can adapt without needing to change the recipe, then I'd suggest a new, _different_ input variable like APPLICATION_NAME or similar.

**Comment by rtrouton** [comment]
I've added new variables to the .download and .pkg recipes, where %NAME% is no longer referenced as a variable in either the .download or .pkg recipe. Override away!
