### ISSUE TITLE
Remove GitHubReleasesInfoProvider.py as custom processor

### ISSUE THREAD

**Issue by tcinbis** [autopkg/rtrouton-recipes#21]
Hello,

because of issue [#408](https://github.com/autopkg/autopkg/issues/408) in autopkg it would be great to remove the GitHubReleasesInfoProvider as custom Processor and instead use the already included Processor of autopkg. 

For example in `AutoPkg-Release` folder [here](https://github.com/autopkg/rtrouton-recipes/tree/master/AutoPkg-Release).

**Comment by rtrouton** [comment]
Older custom processor has been removed from the `AutoPkg-Release` recipe. Now using the built-in `GitHubReleasesInfoProvider` processor.

**Comment by tcinbis** [comment]
@rtrouton thanks!
