### ISSUE TITLE
VMware tools package scripts does not work with AutoDMG

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/rtrouton-recipes#22]
Package scripts from current release of VMware tools do not take into account any other target than `/`.

This is a problem when I want to crate neverbooted macOS image with AutoPKG and use vfuse to convert it to .vmdk.

Should we fix this?

part of postinstall script:
```rm -rf /Library/Filesystems/vmhgfs.fs
mkdir -p /Library/Filesystems/vmhgfs.fs/Contents/Resources
ln -s '/Library/Application Support/VMware Tools/mount_vmhgfs' \
   /Library/Filesystems/vmhgfs.fs/Contents/Resources/
if [ "$macosMajor" -lt 15 ]; then
   rm -f /sbin/mount_vmhgfs
   ln -s '/Library/Application Support/VMware Tools/mount_vmhgfs' /sbin/
fi

sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true
```

**Comment by rtrouton** [comment]
No. AutoDMG warns in its FAQ that it has issues with packages which includes scripts:

[https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment](https://github.com/MagerValp/AutoDMG/wiki/Packages-Suitable-for-Deployment)

Instead, I recommend installing VMware Tools during the VM’s first boot. I have a script available for automatically downloading and installing the latest VMware Tools available here:

[https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/install_latest_vmware_tools](https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/install_latest_vmware_tools)

I also have a tool available for creating firstboot install packages, available here:

[https://github.com/rtrouton/First_Boot_Package_Install_Generator](https://github.com/rtrouton/First_Boot_Package_Install_Generator)
