### ISSUE TITLE
Sophos Home URL No Longer Valid

### ISSUE THREAD

**Issue by foigus** [autopkg/rtrouton-recipes#23]
The [URL to download Sophos home](https://github.com/autopkg/rtrouton-recipes/blob/master/SophosAntiVirusHomeEdition/SophosAntiVirusHomeEdition.download.recipe#L14) is no longer valid.

It appears that Sophos has everything gated behind a login now, and the Sophos Home installer that's available for download ties back to the account that was used to download it.  Once installed, Sophos Home returns back to the Sophos website _under the account that downloaded the Sophosfor preferences and management.

**Comment by rtrouton** [comment]
I'm not seeing a good way to fix this, so I'm going to pull the recipe.

**Comment by rtrouton** [comment]
The following recipes have now been removed:

```
SophosAntiVirusHomeEdition.download.recipe
SophosAntiVirusHomeEdition.install.recipe
SophosAntiVirusHomeEdition.pkg.recipe
SophosAntiVirusHomeEdition.jss.recipe
```
