### ISSUE TITLE
OpenJDK 11 & 12 recipes fail

### ISSUE THREAD

**Issue by beatlemike** [autopkg/rtrouton-recipes#36]
"Error in local.jss.OpenJDK12: Processor: URLTextSearcher: Error: No match found on URL: https://jdk.java.net/12/index.html"

**Comment by rtrouton** [comment]
Problem should now be fixed. Please run `autopgk repo-update rtrouton-recipes`  on your end and try again.

**Comment by beatlemike** [comment]
Worked perfectly, thanks!
