### ISSUE TITLE
New VMware Horizon Client icon

### ISSUE THREAD

**Issue by smashism** [autopkg/rtrouton-recipes#37]
Hullo! Version 5 of VMware Horizon Client introduced a new icon:

<img width="256" alt="install" src="https://user-images.githubusercontent.com/7853266/59464560-6358af00-8dee-11e9-962c-ffa4815b7e55.png">

I don't seem to have permissions to fork/update the icon myself.

**Comment by rtrouton** [comment]
New icon has been uploaded to the repo:

[https://github.com/autopkg/rtrouton-recipes/commit/06e6a1d821ef1ac223940689e47e705c7e77dce4](https://github.com/autopkg/rtrouton-recipes/commit/06e6a1d821ef1ac223940689e47e705c7e77dce4)
