### ISSUE TITLE
Adobe Creative Cloud .pkg download moved

### ISSUE THREAD

**Issue by shanebombbomb** [autopkg/rtrouton-recipes#51]
Running the recipe throws this error:

No match found on URL: https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html

Looks like adobe moved things around again.

**Comment by rtrouton** [comment]
They did, two months ago:

[https://github.com/autopkg/rtrouton-recipes/commit/3557a902bb9596ae2293dd0b5b688f2bd68489c5](https://github.com/autopkg/rtrouton-recipes/commit/3557a902bb9596ae2293dd0b5b688f2bd68489c5)

You may want to update your AutoPkg repos using the following command:

`autopkg repo-update rtrouton-recipes`
