### ISSUE TITLE
Privileges.pkg recipe change on 2020-01-11 introduced Scripts directory dependency

### ISSUE THREAD

**Issue by sdagley** [autopkg/rtrouton-recipes#62]
The change to the Privileges.pkg recipe made on 2020-01-11 defines a INSTALLERSCRIPTS key with the path %RECIPE_DIR%/Scripts, but when the recipe is overriden that directory now refers to the RecipeOverrides directory rather than the parent recipe directory which causes the following error when it's run:

Error in local.pkg.Override-Privileges: Processor: PkgCreator: Error: Can't find scripts directory: /Some/Path/To/AutoPkg/RecipeOverrides/Scripts

Is that an intended behavior with this change?

**Comment by rtrouton** [comment]
Yes. This change was requested because another person's override wasn't successfully finding the `Scripts` directory in the previous rev of the recipe..

**Comment by sdagley** [comment]
With the current setting for the INSTALLERSCRIPTS key you have a Scripts directory at the top level of the RecipeOverrides directory containing postinstall and preinstall script files specific to creating the Privileges package. I'd suggest that %RECIPE_DIR%/Scripts/Privileges makes more sense as it moves those files into a directory specific to Privileges.

**Comment by rtrouton** [comment]
I've changed the default `INSTALLERSCRIPTS` Input value from `%RECIPE_DIR%/Scripts` to `Scripts`., which should put it back to the behavior it had before.

**Comment by smashism** [comment]
@sdagley the recipe as it worked previously did not build a package with scripts because it was looking for Scripts in the RecipeOverrides directory. Was this working correctly for you before any changes were made?

**Comment by sdagley** [comment]
Yes, the .pkg was building with the preinstall and postinstall scripts from the parent recipe's Scripts directory prior to the change on 2020-01-11. It was the change on 2010-01-11 that made it look in the RecipeOverrides/Scripts
