### ISSUE TITLE
Prism.download.recipe fails

### ISSUE THREAD

**Issue by jc0b** [autopkg/rtrouton-recipes#65]
Since updating to AutoPkg 2.0.2, I get a traceback when trying to run the download recipe for Prism 8. 

plistlib raises an error after mounting the dmg because the plist at input_plist_path isn't valid.

`Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/Versioner.py", line 70, in main
    plist = plistlib.load(f)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 944, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file`

My input_plist_path is as follows:
`Users/jacobburley/Library/AutoPkg/Cache/com.github.rtrouton.download.Prism/downloads/Prism.dmg/Prism 8.app/Contents/version.plist`

**Comment by rtrouton** [comment]
Changed recipe so that it's now checking `Prism 8.app/Contents/Infoplist` for the version info.

**Comment by jc0b** [comment]
This fixed my issue, thanks! I'll close this issue now.
