### ISSUE TITLE
Error in local.munki.MalwareBytesAntiMalware: Processor: Unarchiver: Error: Unarchiving

### ISSUE THREAD

**Issue by sau70networkadmin** [autopkg/rtrouton-recipes#7]
Hi,

Apologies if this is the wrong place/way to ask this question. I have a Mac server running 10.10.5 with XCode Command Line Tools version 7.2. I am attempting to run the MalwareBytesAntiMalware recipe, and this is what happens:

beavis:AutoPkg admin$ autopkg repo-add autopkg/rtrouton-recipes
Attempting git pull...
Updating 4b3b595..f2c424d
Fast-forward
 JSS/Dropbox.png                                     | Bin 85830 -> 42556 bytes
 JSS/GoogleChrome.jss.recipe                         |   2 ++
 .../MalwarebytesAntiMalware.install.recipe          |   4 +---
 3 files changed, 3 insertions(+), 3 deletions(-)

Adding /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.aanklewicz-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.aysiu-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes'
beavis:AutoPkg admin$ autopkg make-override MalwareBytesAntiMalware.munki
Override file saved to /Users/admin/Library/AutoPkg/RecipeOverrides/MalwareBytesAntiMalware.munki.recipe
beavis:AutoPkg admin$ vim RecipeOverrides/MalwareBytesAntiMalware.munki.recipe
	(my only change was to add catalog "main")
beavis:AutoPkg admin$ autopkg run MalwareBytesAntiMalware.munki
Processing MalwareBytesAntiMalware.munki...
Unarchiving /Users/admin/Library/AutoPkg/Cache/local.munki.MalwareBytesAntiMalware/downloads/mbam-mac-1.1.3.72.zip with ditto failed: ditto: /Users/admin/Library/AutoPkg/Cache/local.munki.MalwareBytesAntiMalware/Malwarebytes/Malwarebytes Anti-Malware.app/Contents/Frameworks/Sparkle.framework/Headers: Is a directory
ditto: Unknown compression type

Failed.

The following recipes failed:
    MalwareBytesAntiMalware.munki
        Error in local.munki.MalwareBytesAntiMalware: Processor: Unarchiver: Error: Unarchiving /Users/admin/Library/AutoPkg/Cache/local.munki.MalwareBytesAntiMalware/downloads/mbam-mac-1.1.3.72.zip with ditto failed: ditto: /Users/admin/Library/AutoPkg/Cache/local.munki.MalwareBytesAntiMalware/Malwarebytes/Malwarebytes Anti-Malware.app/Contents/Frameworks/Sparkle.framework/Headers: Is a directory
ditto: Unknown compression type

The following new items were downloaded:
    Download Path                                                                                           
    -------------                                                                                           
    /Users/admin/Library/AutoPkg/Cache/local.munki.MalwareBytesAntiMalware/downloads/mbam-mac-1.1.3.72.zip  

What should I do? 

Thank you very much!

-- MB

**Comment by rtrouton** [comment]
I'm not certain which recipe you were building your override from, as I don't have a .munki recipe available for MalwareBytes. There is a .munki recipe available via the link below:

https://github.com/autopkg/aysiu-recipes/blob/master/MalwarebytesAntiMalware/MalwarebytesAntiMalware.munki.recipe

**Comment by sau70networkadmin** [comment]
Hi Rich,

Holy buckets, I'm so confused:

-------------
beavis:AUTOPKG admin$ autopkg repo-delete rtrouton-recipes
beavis:AUTOPKG admin$ autopkg repo-add aysiu-recipes
Attempting git clone...
Adding
/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.aysiu-recipes
to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.aanklewicz-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes'

'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.aysiu-recipes'

beavis:AUTOPKG admin$ autopkg make-override MalwareBytesAntiMalware.munki
Didn't find a recipe for
com.github.rtrouton.download.MalwarebytesAntiMalware.
Search GitHub AutoPkg repos for a
com.github.rtrouton.download.MalwarebytesAntiMalware recipe? [y/n]:
-------------

That's what happened before, and I thought I could make it happy by adding
your repo. Could you help me understand what's going on here, or, advise me
on where/how to ask?

Thank you very much!

-- MB

**Comment by rtrouton** [comment]
Ah, I see the issue. The MalwarebytesAntiMalware.munki recipe is not hosted in my repo, but it is using the MalwarebytesAntiMalware.download recipe hosted in my repo (rather than re-invent the wheel and build a separate download recipe for MalwareBytes):

https://github.com/autopkg/aysiu-recipes/blob/master/MalwarebytesAntiMalware/MalwarebytesAntiMalware.munki.recipe#L37-L38

So you do need both the **rtrouton-recipes** and **aysiu-recipes** repos in order to import Malwarebytes into your Munki repo. That said, your issue appears to be coming from the MalwarebytesAntiMalware.munki recipe hosted in the **aysiu-recipes** repo, so the place to open an issue is over at the **aysiu-recipes** repo, not here at the **rtrouton-recipes** repo.

**Comment by sau70networkadmin** [comment]
Ahhh OK -- thank you VERY much!

-- MB
