### ISSUE TITLE
Fiji download recipe broken by change to release notes format

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/rtrouton-recipes#81]
The Fiji recipe now fails with an error:

Error in local.munki.Fiji: Processor: PkgCreator: Error: Invalid version component ""

This appears to be due to the version RE in Fiji.download.recipe no longer matching what is on https://imagej.nih.gov/ij/notes.html which now reads:

Version >1.53e 16 September 2020

The > seems to be new and I assume this is what is breaking the RE.

**Comment by rtrouton** [comment]
Fixed by PR [https://github.com/autopkg/rtrouton-recipes/pull/84](https://github.com/autopkg/rtrouton-recipes/pull/84).
