### ISSUE TITLE
AdobeCreativeCloud download dmg URL changed, gets older version

### ISSUE THREAD

**Issue by rrenstrom** [autopkg/rtrouton-recipes#82]
In AdobeCreativeCloud/AdobeCreativeCloudInstaller.download.recipe 

Not sure if this is just a temporary mistake by Adobe, but the URL for the current download is http (instead of https) on their download page (https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html).

There are two dmg download links on this page, so URLTextSearcher is matching the second download link (which is still https, but for the older version 4):

macOS v10.12 or later href="http://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_3_0/osx10/ACCCx5_3_0_468.dmg" 

macOS v10.11 or earlier href="https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/4_9/osx10/ACCCx4_9_0_504.dmg" 

Fix I've applied is to match either http or https

```
        <key>SEARCH_PATTERN</key>
<string>(?P&lt;url&gt;http.*://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/.*?/osx10/ACCC.*?.dmg)</string>

```

**Comment by Darks7ar** [comment]
Second this. It's currently grabbing v4.9.0

**Comment by rtrouton** [comment]
Updated regex to match what @rrenstrom is using and I've verified that the `AdobeCreativeCloudInstaller.download.recipe` is now pulling the `ACCCx5_3_0_468.dmg` disk image.
