### ISSUE TITLE
ImageJ Versioning

### ISSUE THREAD

**Issue by vmiller** [autopkg/rtrouton-recipes#86]
Recent [https://github.com/autopkg/rtrouton-recipes/commit/77cf713ce0f86f2c977e94672e2f94b224da68b3](commit) to the ImageJ affects how version is determined.  This results in the version for the latest ImageJ being set to 1.53 when the ImageJ page lists 1.53e

It's unfortunate that the full version is not set in CFBundleShortVersionString in the app bundle.  Version can probably still be scraped from https://imagej.nih.gov/ij/notes.html even if it is no longer being used to build the download URL.

Thoughts @macmule @Daz-wallace ?

**Comment by Daz-wallace** [comment]
Ideally the vender wouldn't do silly things 😉 

I've scanned over the notes page and it looks like the do indeed use the letter to denote different minor versions (e.g. 1.53e and 1.53d are newer and older versions of the app respectively). 

I guess that is what [this section](https://github.com/autopkg/rtrouton-recipes/commit/77cf713ce0f86f2c977e94672e2f94b224da68b3#diff-c228b2b4fe6ac76c52bb10dd80a24065L18-L28) was doing but, to be honest I struggled to understand the logic and how it was passing that value through the recipe/s previously.

Any thoughts on a PR? 😉

**Comment by vmiller** [comment]
I'm willing to take a crack at a PR.  I just wanted to start a discussion first to make sure I wasn't missing anything.

**Comment by Daz-wallace** [comment]
Sure, I'm just having a dig now too. 😊 

I guess another discussion is what is more important or accurate: The version from their website, or the version number of what's deployed to disk?

**Comment by vmiller** [comment]
That's a valid question.  It is not clear from how the download URL is constructed whether it is always the latest build, or whether it is a base version that will be updated after install.

**Comment by Daz-wallace** [comment]
Looking at the current download URL on https://imagej.nih.gov/ij/download.html it's the major version that is downloaded (e.g. v1.53, no v1.53e).

IMHO I'd suggest the version on disk is more important, but I'm not a user of the software per-say so I don't know if that causes more issues?

**Comment by vmiller** [comment]
Like you, I am also not a user of the software.

I would not trust ImageJ.app/Contents/Info.plist to contain the truth of what version is deployed to disk.  I'm looking at some prior versions in my munki repo, and the hash of lj.jar differs even when Info.plist is not updated.

Curiously, the use of CFBundleShortVersionString is new.  The prior versions I have handy have CFBundleVersion set to 10.2 (for 1.53c and 1.53d)
