### ISSUE TITLE
VMware Horizon PKG recipe strips xattr from files

### ISSUE THREAD

**Issue by staze** [autopkg/rtrouton-recipes#91]
Looks like the InitUsbServices.tool file and a few others inside the Horizon client have some xattr's set (codesigning looks like) that Autopkgr is stripping, and so horizon says the file is invalid. 

Not sure if this is an Autopkgr inherent issue, or if it can be addressed in the recipe. For now, having to package the DMG, then mount and copy over the application via postinstall.

**Comment by staze** [comment]
Hi @rtrouton. Curious about this being closed. did issue get resolved? I'm not seeing any change in the recipe.

**Comment by rtrouton** [comment]
No, I don't have a solution so I'm going to remove those recipes.

**Comment by staze** [comment]
No worries. Sorry to hear that, but makes sense.

**Comment by rtrouton** [comment]
Deprecation warning now added, so folks at least know what's happening.

[https://github.com/autopkg/rtrouton-recipes/commit/5bc1e51c242ba294d94f0ef45abbc1098095d359](https://github.com/autopkg/rtrouton-recipes/commit/5bc1e51c242ba294d94f0ef45abbc1098095d359)
