### ISSUE TITLE
Universal-version of MSEdge available, please update the recipe

### ISSUE THREAD

**Issue by JakoVerstraate** [autopkg/rtrouton-recipes#96]
since version 88, Microsoft Edge is available in a Universal-version next to the Intel-version.
On https://www.microsoft.com/en-us/edge/business/download you can choose: 
-version (Stable 88)
-Build 
-Platform (macOS Universal or Intel)
the recipe now downloads the Intel-version, please update the recipe to download the Universal-version

**Comment by rtrouton** [comment]
What's the download URL?

**Comment by JakoVerstraate** [comment]
as you might have read on Slack (channel #autopkg) the new URL is https://go.microsoft.com/fwlink/?linkid=2093504

**Comment by rtrouton** [comment]
Recipe has been updated: [https://github.com/autopkg/rtrouton-recipes/commit/94bb3b9cbe49eca82aafd75665bf944f26438532#diff-d2a84c90524363864e1feb205eed023ce77ba7223e1422bab06b49bb804830cc](https://github.com/autopkg/rtrouton-recipes/commit/94bb3b9cbe49eca82aafd75665bf944f26438532#diff-d2a84c90524363864e1feb205eed023ce77ba7223e1422bab06b49bb804830cc)
