### ISSUE TITLE
AdobeCreativeCloudInstaller - URLDownloader error

### ISSUE THREAD

**Issue by skoobasteeve** [autopkg/rtrouton-recipes#98]
Hello,
This morning I had an error in my Adobe Creative Cloud recipe:

`Error in local.jss.AdobeCreativeCloudInstaller-riskified: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_3_1/osx10/ACCCx5_3_1_470.dmg" disablelinktracking="false">Download&nbsp;</a><a href="https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_3_1/osx10/ACCCx5_3_1_470.dmg', '--fail', '--output', '/Users/riskiadmin/Library/AutoPkg/Cache/local.jss.AdobeCreativeCloudInstaller-riskified/downloads/tmpcr8jzlgk', '--header', 'If-None-Match: "b35e929fd2858b12e955c8b44c8f3289:1602510778.89782"', '--header', 'If-Modified-Since: Mon, 12 Oct 2020 12:06:50 GMT']' returned non-zero exit status 22`

I tried running URLDownloader.py directly with the arguments above and got this error (probably explains the exit status 22):

`Traceback (most recent call last):
  File "./URLDownloader.py", line 22, in <module>
    from autopkglib import BUNDLE_ID, ProcessorError, is_mac
ModuleNotFoundError: No module named 'autopkglib'`

The Adobe URL works fine if I call it directly, so not sure what's going on here. No errors in my other recipes.

**Comment by joncrain** [comment]
Manually running the curl command returns `curl: (22) The requested URL returned error: 503 `.

Adding `-v`

```
*   Trying 184.25.116.81...
* TCP_NODELAY set
* Connected to ccmdl.adobe.com (184.25.116.81) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [229 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2543 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [148 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Jose; O=Adobe Inc; CN=*.adobe.com
*  start date: Feb  2 00:00:00 2021 GMT
*  expire date: Feb  6 23:59:59 2022 GMT
*  subjectAltName: host "ccmdl.adobe.com" matched cert's "*.adobe.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f941b80f800)
> GET /AdobeProducts/KCCC/CCD/5_3_1/osx10/ACCCx5_3_1_470.dmg disablelinktracking=false>Download&nbsp;</a><a href=https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_3_1/osx10/ACCCx5_3_1_470.dmg HTTP/2
> Host: ccmdl.adobe.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* The requested URL returned error: 503 
* stopped the pause stream!
* Connection #0 to host ccmdl.adobe.com left intact
curl: (22) The requested URL returned error: 503 
* Closing connection 0```

**Comment by vdesouza** [comment]
Opened a PR to address this https://github.com/autopkg/rtrouton-recipes/pull/99

**Comment by skoobasteeve** [comment]
#99 solved it! Thanks everyone for your help.
